# Generated by Django 5.1.1 on 2024-09-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicefile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
