# Generated by Django 5.1.1 on 2024-10-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicefile', '0005_banner_remove_teacher_student_remove_teacher_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
