# Generated by Django 5.1.1 on 2024-10-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicefile', '0011_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
